@server = http://localhost:3000

### permitted
GET {{server}}/permitted
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE1MjQ4OTMzMTMsImV4cCI6MTUyNTQ5ODExM30.CAKXAgtiIEfIfVCRkKYGIRv4Kom61qOQbWuFkS4kVRo

### not permitted
GET {{server}}/permitted
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2MjQ4OTI1NjksImV4cCI6MTUyNTQ5NzM2OX0.wcI7W1Clp9XWFz15FjBSC44dmdeixTuOxgjKIMqRpyY
 
### Auth login
POST {{server}}/login
?email=ruegen@example.com&password=elephant

### not auth login no password
POST {{server}}/login

### not auth login wrong password
POST {{server}}/login
?email=ruegen@example.com&password=mac
